"""Project briefs rendered by build-pages.py with its shared navigation and asset versions."""
from html import escape

projects = [
    dict(slug='applied-ai', label='DICONIUM / APPLIED AI', title='Make AI useful.<br><em>Then make it usable.</em>',
         intro='I build AI products and lead the cross-functional team that takes them from discovery into use. The work spans product strategy, hands-on engineering, evaluation, and adoption.',
         role='Principal Specialist AI · AI R&D team lead', period='2022–present at diconium', scope='Enterprise AI · Product strategy · Engineering', image='knowledge-map.svg', alt='Conceptual map of information connected through an AI system',
         problem='An AI capability becomes useful when it fits the work people actually need to do. At diconium, my remit connects user needs and business decisions with the systems, evaluation, and rollout required to put AI into production.',
         steps=[('Build the team and the product practice.', 'Created and lead a seven-person AI R&D team spanning data science, business analysis, UX, and product strategy. My responsibility covers discovery through architecture, implementation, guardrails, rollout, and adoption.'),('Stay hands-on across the system.', 'Develop full-stack AI products across LLM and machine-learning pipelines, APIs, backend services, interfaces, databases, and cloud infrastructure. Work includes enterprise knowledge assistants, multimodal knowledge platforms, and natural-language analytics.'),('Connect technical work to business decisions.', 'Work on AI roadmaps and maturity models alongside product delivery. This includes a Volkswagen AI roadmap and a proof of concept connected to a data-platform opportunity.')],
         results=[('7 people', 'Cross-functional AI R&D team'),('−80%', 'Time to insight in a natural-language analytics initiative'),('60 → 85%', 'Documentation satisfaction in enterprise assistant work')],
         outcome='These results refer to separate initiatives, as reported in my CV. Enterprise assistant work also reduced time to find information from days to minutes and supported more than five use cases, including medical and pharmaceutical contexts.',
         sources=[('https://special.diconium.com/en/dicobot-ai-chatbot/alpha', 'diconium: public interview about Dicobot’s alpha phase')], next='meuccitech', nextname='Meuccitech'),
    dict(slug='meuccitech', label='MEUCCITECH / VENTURE', title='An AI capability.<br><em>A working business.</em>',
         intro='As founder and CEO of Meuccitech, I took an AI audiobook production platform from concept to commercial delivery, building alongside our CTO.',
         role='Founder & CEO · Product and technical delivery', period='2023–present', scope='Voice AI · Production workflows · Commercial delivery', image='audio-pipeline.svg', alt='Conceptual audio waveform representing the audiobook production workflow',
         problem='Generating a voice is one part of producing an audiobook. A commercial workflow also needs processing, review, quality assurance, and a dependable path from an uploaded book to finished audio.',
         steps=[('Turn the concept into a production platform.', 'Built the platform alongside the CTO, connecting voice AI and automated processing with human review and quality assurance.'),('Own the commercial side as well as the product.', 'Led the venture from concept to production with commercial partners, including an agreement with SAGA and work with a high-volume self-publishing platform.'),('Deliver the finished work.', 'Operated a production workflow that has delivered more than 1,000 hours of commercial AI-generated audio. Delivery time is measured from upload to final completion.')],
         results=[('1,000+ h', 'Commercial AI-generated audio delivered'),('4.8 days', 'Average upload-to-final time for completed projects'),('92%', 'Completed within two weeks')],
         outcome='The delivery figures are reported in my CV and describe completed production projects. The work combines technical implementation, product ownership, partner relationships, and operational delivery.',
         sources=[('https://www.meucci.org', 'Meuccitech website')], next='rehality', nextname='Rehality'),
    dict(slug='rehality', label='REHALITY / NEUROSCIENCE & XR', title='From the nervous system<br><em>to an interactive system.</em>',
         intro='Post-stroke rehabilitation research at the intersection of neuroscience, extended reality, machine learning, and real-time biosignal feedback.',
         role='Project lead & co-founder', period='2017–2022', scope='Research translation · XR · Consortium leadership', image='rehality-loop.svg', alt='Conceptual biosignal and movement feedback loop',
         problem='Rehabilitation research connects several kinds of expertise: the clinical question, the person moving, the signals being measured, and the interface that responds. Rehality brought those disciplines together in adaptive prototypes and clinical study design.',
         steps=[('Connect signals to interactive prototypes.', 'Worked with XR, machine learning, EEG, EMG, and eye tracking to develop real-time biosensor feedback for post-stroke rehabilitation research.'),('Bring the disciplines together.', 'Led a four-partner consortium across academic, clinical, engineering, and industry expertise, and helped secure BMBF grant funding.'),('Keep research and application connected.', 'Combined adaptive prototyping with clinical study design. This work sat alongside my doctoral training in neural and behavioral sciences at the University of Tübingen and Max Planck Institute.')],
         results=[('4 partners', 'Academic, clinical, engineering, and industry collaboration'),('BMBF', 'Grant-funded research'),('XR + signals', 'Adaptive rehabilitation prototypes')],
         outcome='The contribution here is research translation, prototype development, and consortium leadership. These are not claims of established patient benefit or clinical efficacy.',
         sources=[('../../science/', 'Research papers and presentations'),('https://www.youtube.com/watch?v=8Jv4oByOR0g', 'Virtual Reality Based Neurorehabilitation — DGKN 2021')], next='babybaby', nextname='BabyBaby'),
    dict(slug='babybaby', label='BABYBABY / INDEPENDENT PRODUCT', title='Build for the person<br><em>on the other side.</em>',
         intro='A companion for new parents that brings daily care tracking, personalized insights, questions, and memory books into one connected experience.',
         role='Creator · Product, design & engineering', period='2026–present', scope='Product discovery · Full-stack development · AI', image='../../business/baby-app-images/BabyBabyApp_page1.png', alt='BabyBaby daily care tracking interface',
         problem='Daily care produces a stream of small observations: feeding, sleep, growth, milestones, and questions. BabyBaby brings that information together so parents can record the day, see patterns, and keep the moments they want to remember.',
         steps=[('Design the connected experience.', 'Designed a product spanning care tracking, personalized insights, evidence-grounded Q&A, and memory books. The existing product gallery shows the interface across these features.'),('Own the build from end to end.', 'Responsible for product direction, UX, architecture, frontend, backend, AI features, deployment, and iteration. Used Codex and Claude Code as part of the development workflow.'),('Take it through launch and iteration.', 'Designed, built, and launched the product. This project demonstrates end-to-end ownership of a working application; adoption and retention figures are not yet included here.')],
         results=[('4 areas', 'Care, questions, memories, and insights'),('End to end', 'Product, UX, engineering, and deployment'),('Launched', 'Working product with ongoing iteration')],
         outcome='See the product gallery for the actual interfaces. The project currently provides evidence of a shipped product and hands-on ownership rather than a claim about measured customer outcomes.',
         sources=[('../../business/babybaby/', 'BabyBaby product screenshots')], next='applied-ai', nextname='Applied AI')
]

for p in projects:
    def e(value): return escape(value, quote=True)
    steps=''.join(f'<li><div><h3>{e(title)}</h3><p>{e(copy)}</p></div></li>' for title,copy in p['steps'])
    results=''.join(f'<div><strong>{e(value)}</strong><span>{e(label)}</span></div>' for value,label in p['results'])
    sources=''.join(f'<li><a href="{e(url)}">{e(label)} ↗</a></li>' for url,label in p['sources'])
    image=p['image'] if p['slug']=='babybaby' else '../../assets/work/'+p['image']
    text=f'''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#f3f0e8"><meta name="description" content="{e(p['intro'])}"><title>{e(p['label'].split(' / ')[0].title())} — Eric James McDermott</title><link rel="icon" href="../../assets/home/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="../../home.css"><link rel="stylesheet" href="../../site.css"><link rel="stylesheet" href="../../portfolio.css"><script src="../../site.js" defer></script></head>
<body class="case-page" id="top"><a class="skip-link" href="#overview">Skip to project</a><div class="reading-progress" aria-hidden="true"></div>{nav('../../')}
<main class="case-main"><section class="case-hero folio-pad"><nav class="case-breadcrumb" aria-label="Breadcrumb"><a href="../../#directory">Selected work</a> / {e(p['label'].split(' / ')[0].title())}</nav><p class="folio-label">{e(p['label'])}</p><h1>{p['title']}</h1><p class="case-lede">{e(p['intro'])}</p><dl class="case-facts"><div><dt>MY ROLE</dt><dd>{e(p['role'])}</dd></div><div><dt>PERIOD</dt><dd>{e(p['period'])}</dd></div><div><dt>SCOPE</dt><dd>{e(p['scope'])}</dd></div></dl></section>
<div class="folio-pad"><img class="case-cover {'case-cover-phone' if p['slug']=='babybaby' else ''}" src="{image}" alt="{e(p['alt'])}" width="900" height="600"></div>
<div class="case-body folio-pad"><nav class="case-aside" aria-label="In this project"><a href="#overview">01 / The context</a><a href="#contribution">02 / My contribution</a><a href="#outcomes">03 / Outcomes</a><a href="#evidence">04 / Evidence</a></nav><div><section class="case-section" id="overview"><p class="folio-label">THE CONTEXT</p><h2>The problem to work on.</h2><p>{e(p['problem'])}</p></section><section class="case-section" id="contribution"><p class="folio-label">MY CONTRIBUTION</p><h2>Where I took responsibility.</h2><ol class="case-steps">{steps}</ol></section><section class="case-section" id="outcomes"><p class="folio-label">WHAT CAME OUT OF IT</p><h2>From intention to evidence.</h2><div class="case-results">{results}</div><p>{e(p['outcome'])}</p></section><section class="case-sources" id="evidence"><p class="folio-label">SOURCES & FURTHER READING</p><p>This brief is based on my professional record. Roles and figures are reported in my CV.</p><ul><li><a href="../../science/EJM-CV.pdf">Curriculum vitae ↗</a></li>{sources}</ul></section></div></div>
<nav class="case-next folio-pad" aria-label="Next project"><span>KEEP EXPLORING</span><a href="../{p['next']}/">{p['nextname']} ↗</a></nav></main><footer class="folio-footer folio-pad"><a href="../../#directory">← All work</a><a href="mailto:EricJamesMcDermott@gmail.com">Let’s talk about what you’re building ↗</a></footer></body></html>'''
    destination=ROOT/'work'/p['slug']
    destination.mkdir(parents=True,exist_ok=True)
    (destination/'index.htm').write_text(version_assets(text)+'\n')
